version: '3.7'
services: 
  web:
    container_name: app_web_1
    restart: always
    build: ./flask-web
    command: bash run_prodmode.sh
    expose: 
      - '5000'
    volumes: 
      - data:/code
  nginx:
    container_name: app_nginx_1
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on: 
      - web
volumes:
  data:
    name: app_data